sudo: false
language: c++
dist: focal
addons:
  apt:
    packages:
      - g++-9
      - cmake
      - libopencv-dev 
      - python3-opencv
      - python3-pip
      - libboost-all-dev
script:
  - mkdir -p build
  - cd build
  - cmake .. 
  - make
